version: "3.7"

x-default-app: &default-app
  RELEASE_NAME: local
  LOCAL_MONGODB_SERVICE_HOST: mongo
  LOCAL_MONGODB_SERVICE_PORT: 27017
  LOCAL_RABBITMQ_SERVICE_HOST: rabbitmq
  LOCAL_RABBITMQ_SERVICE_PORT_AMQP: 5672
  LOCAL_RABBITMQ_SERVICE_PORT_HTTP_STATS: 15672
  LOCAL_USER_SERVICE_RAILS_SERVICE_HOST: 35.192.77.102
  RABBITMQ_USERNAME: $RABBITMQ_USERNAME
  RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD
  SHOPIFY_API_KEY: $SHOPIFY_API_KEY
  SHOPIFY_API_PASSWORD: $SHOPIFY_API_PASSWORD
  SHOPIFY_SHOP_NAME: $SHOPIFY_SHOP_NAME

x-default-volumes: &default-volumes
  - .:/app
  - tmp:/app/tmp
  - bundle:/app/vendor/bundle

networks:
  network:
    driver: bridge

services:
  app:
    environment:
      <<: *default-app
    volumes: *default-volumes
    image: $IMAGE_NAME:$IMAGE_TAG
    networks:
      - network
    ports:
      - "5900:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.5
    restart: always
    ports:
      - "5901:27017"
    networks:
      - network

  hutch:
    restart: always
    environment:
      <<: *default-app
    volumes: *default-volumes
    image: $IMAGE_NAME:$IMAGE_TAG
    networks:
      - network
    command: bundle exec hutch
    depends_on:
      - rabbitmq

  sneakers:
    restart: always
    environment:
      <<: *default-app
    volumes: *default-volumes
    image: $IMAGE_NAME:$IMAGE_TAG
    networks:
      - network
    command: bin/rake sneakers:run
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    environment:
      <<: *default-app
      RABBITMQ_ERLANG_COOKIE: d
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USERNAME
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
    ports:
      - 5942:15672
    networks:
      - network

volumes:
  tmp:
  bundle:
