apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce-store-front.fullname" . }}-configmap
data:
  RELEASE_NAME: {{ .Release.Name }}
  RAILS_ENV: {{ .Values.railsEnv }}
  SECRET_KEY_BASE: {{ .Values.secretKey }}
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.auth.username }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password }}
  SHOPIFY_API_KEY: {{ .Values.shopify_api_key }}
  SHOPIFY_API_PASSWORD: {{ .Values.shopify_api_password }}
  SHOPIFY_SHOP_NAME: {{ .Values.shopify_shop_name }}
  RAILS_LOG_TO_STDOUT: enabled