production:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "ecommerce-store-front_production") %>

development:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "ecommerce-store-front_development") %>

test:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "ecommerce-store-front_test") %>
