{{- if .Values.sneakers.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ecommerce-store-front.fullname" . }}-sneakers
  labels:
    {{- include "ecommerce-store-front.labels" . | nindent 4 }}-sneakers
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ecommerce-store-front.fullname" . }}-sneakers
  minReplicas: {{ .Values.sneakers.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sneakers.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.sneakers.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.sneakers.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.sneakers.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.sneakers.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
